Coopreport/Coopreport/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Coopreport.Models;

namespace Coopreport.Controllers
{
    [Authorize(Roles = "Student")]
    public class ReportController : Controller
    {
        private CoopreportContext db_context = new CoopreportContext();
        // GET: Reports
        public ActionResult Index()
        {
            var reports = db_context.Report.ToList();
            if (reports.Count == 0)
            {
                ViewBag.msg = "So far, no reports submitted";
            }
            return View(reports);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var firstname = db_context.User.Where(x => x.Username == User.Identity.Name).FirstOrDefault().FirstName;
            var lastname = db_context.User.Where(x => x.Username == User.Identity.Name).FirstOrDefault().LastName;
            ViewBag.fullname = firstname + " " + lastname;
            ViewBag.name = User.Identity.Name;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Report report)
        {
            if(ModelState.IsValid){
                db_context.Report.Add(report);
                db_context.SaveChanges();
                return Redirect("index");
            }
            return View(report);
        }
    }
}

Coopreport/Coopreport/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Coopreport.Models;
using System.Web.Security;
using System.Net;
using System.Data.Entity;

namespace Coopreport.Controllers
{
    public class UserController : Controller
    {
        List<User> user_Info = new List<User>();

        public UserController() { }
        public UserController(List<User> user_Info) {
            this.user_Info = user_Info;
        }
        private CoopreportContext db_context = new CoopreportContext();
        // GET: User
        [Authorize(Roles = "Student")]
        public ActionResult Index()
        {
            var userid = db_context.User.Where(x => x.Username == User.Identity.Name).FirstOrDefault().UserID;
            User user = db_context.User.Find(userid);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(user);
        }
        [HttpPost]
        [Authorize(Roles="Student")]
        public ActionResult Index(User user)
        {
            if (ModelState.IsValid)
            {
                db_context.Entry(user).State = EntityState.Modified;
                db_context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult Login()
        {
            return View();
        }

        public IEnumerable<User> GetUsers() {
            return user_Info;
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            var login = db_context.User.Where(x => x.Username == user.Username && x.Password == user.Password).Count();
            if (login != 0)
            {
                FormsAuthentication.SetAuthCookie(user.Username, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Msg = "Invalid User Credentials";
                return View();
            }

        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                db_context.User.Add(user);
                db_context.SaveChanges();
                return Redirect("Login");
            }
            return View();
        }
    }
}

Coopreport/Coopreport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CO-OP Report", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Student"))
                        {
                            <li>@Html.ActionLink("Update Profile", "Index", "User")</li>
                            <li>@Html.ActionLink("COOP Report","Index","Report")</li>
                        }
                    }
                    else
                    {
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Employer Eval Form", "Index", "EmpEvaForms")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Welcome:" + User.Identity.Name, "")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Register", "Register", "User")</li>
                        <li>@Html.ActionLink("Login", "Login", "User")</li>
                    }
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Centennial College CO-OP Report</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>